[tool.poetry]
name = "theapp"
version = "0.1.0"
description = "TBS1 App"
authors = ["Marco Bakera <marco@bakera.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
